/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowlcreatorkata;

import java.util.Arrays;
import java.util.List;

public class App {
    public static void main(String[] args) {
        Ingredient ingredient1 = new Ingredient(IngredientEnum.BROWN_RICE.getName());
        Ingredient ingredient2 = new Ingredient(IngredientEnum.MUSHROOMS.getName());

        List<Ingredient> ingredients = List.of(ingredient1, ingredient2);

        try {
            createBuddhaBowl(ingredients);
        } catch (BuddhaBowlException e) {
            System.out.println("Failed to create Buddha Bowl: " + e.getMessage());
        }
    }

    public static BuddhaBowl createBuddhaBowl(List<Ingredient> ingredients) throws BuddhaBowlException {
        if (!checkIfIngredientsMix(ingredients)) {
            throw new BuddhaBowlException("Ingredients do not mix well together");
        }
        return new BuddhaBowl(ingredients);
    }

    public static boolean checkIfIngredientsMix(List<Ingredient> ingredients) {
        List<List<String>> incompatiblePairs = Arrays.asList(
                Arrays.asList(IngredientEnum.TOFU.getName(), IngredientEnum.YOGURT_DRESSING.getName()),
                Arrays.asList(IngredientEnum.OATS.getName(), IngredientEnum.MUSHROOMS.getName()),
                Arrays.asList(IngredientEnum.KALE.getName(), IngredientEnum.WHEAT.getName()),
                Arrays.asList(IngredientEnum.HAZELNUTS.getName(), IngredientEnum.TAHINI_LEMON_DRESSING.getName()));

        for (List<String> pair : incompatiblePairs) {
            if (ingredients.stream().anyMatch(ingredient -> ingredient.getName().equals(pair.get(0))) &&
                    ingredients.stream().anyMatch(ingredient -> ingredient.getName().equals(pair.get(1)))) {
                return false;
            }
        }

        return true;
    }
}